Jobseeker/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('daftar/P<int:job_id>', views.testFrontEnd, name='daftar'),
    path('listDilamar', views.listDilamar, name='pekerjaanDidaftar'),
    path('listDilamar/ajaxFtime', views.ajaxFtime, name='ajaxFtime'),
    path('listDilamar/ajaxPtime', views.ajaxPtime, name='ajaxPtime'),
    path('listDilamar/ajaxIntern', views.ajaxIntern, name='ajaxIntern'),

]

TK_PPW_C09/urls.py
from django.contrib import admin
from django.urls import path, include
from TK1_PPW import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('TK1_PPW.urls'), name='LandingPage'),
    path('Jobseeker/', include('Jobseeker.urls'), name='Jobseeker'),
    path('Kantor/', include('Kantor.urls'), name='Kantor'),
    path('VolunteerNonPerawat/', include('VolunteerNonPerawat.urls'),
         name='VolunteerNonPerawat'),
    path('RumahSakit/', include('RumahSakit.urls'), name='RumahSakit'),
    path('Perawat/', include('Perawat.urls'), name='Perawat'),
    path('login/', include('login.urls'), name='login')
]

login/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('', views.index, name='story9index'),
    path('register/', views.register, name="register"),
    path('login/', views.loginCustom, name='login'),
    path('logout/', views.logoutCustom, name='logout'),
    path('editProfile/', views.editProfile, name='editProfile'),
    path('rLogout/', views.rLogout, name='registerLogout')
]

Jobseeker/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from Kantor.models import Kantor
# Create your models here.


class Jobseeker(models.Model):
    LAST_ED = (
        ('MA', 'SMA'),
        ('S1', 'Sarjana'),
        ('S2', 'Pascasarjana'),
    )

    PROVINSI = (
        ('1', 'Aceh'),
        ('2', 'Sumatera Utara'),
        ('3', 'Sumatera Barat'),
        ('4', 'Riau'),
        ('5', 'Kepulauan Riau'),
        ('6', 'Bengkulu'),
        ('7', 'Jambi'),
        ('8', 'Sumatera Selatan'),
        ('9', 'Bangka Belitung'),
        ('10', 'Lampung'),
        ('11', 'Banten'),
        ('12', 'Jawa Barat'),
        ('13', 'Jakarta'),
        ('14', 'Jawa Tengah'),
        ('15', 'Di Yogyakarta'),
        ('16', 'Jawa Timur'),
        ('17', 'Bali'),
        ('18', 'Nusa Tenggara Barat'),
        ('19', 'Nusa Tenggara Timur'),
        ('20', 'Kalimantan Timur'),
        ('21', 'Kalimantan Barat'),
        ('22', 'Kalimantan Selatan'),
        ('23', 'Kalimantan Tengah'),
        ('24', 'Kalimantan Utara'),
        ('25', 'Gorontalo'),
        ('26', 'Sulawesi Barat'),
        ('27', 'Sulawesi Tengah'),
        ('28', 'Sulawesi Selatan'),
        ('29', 'Sulawesi Tenggara'),
        ('30', 'Sulawesi Utara'),
        ('31', 'Maluku'),
        ('32', 'Maluku Utara'),
        ('33', 'Papua Barat'),
        ('34', 'Papua'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nama_pelamar = models.CharField(max_length=64)
    umur_pelamar = models.IntegerField(
        validators=[
            MaxValueValidator(55),
            MinValueValidator(17)
        ], blank=True, null=True)
    pekerjaan_dilamar = models.ManyToManyField(
        Kantor, related_name='pelamar')
    provinsi_pelamar = models.CharField(
        max_length=2, choices=PROVINSI, blank=True)
    kota_pelamar = models.CharField(max_length=15, blank=True)
    pendidikan_terakhir = models.CharField(
        max_length=2, choices=LAST_ED, blank=True)

    def __str__(self):
        return self.nama_pelamar

Jobseeker/forms.py
from django import forms


class FormPelamar(forms.Form):

    nama_pelamar = forms.CharField(
        label="Nama",
        max_length=64,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    umur_pelamar = forms.IntegerField(
        label="Umur",
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'min': '17',
                'max': '55',
                'id': 'umur_pelamar'
            }
        )
    )

    kota_pelamar = forms.CharField(
        label="Asal Kota",
        max_length=200,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'id': 'kota_pelamar'

            }
        )
    )

    pendidikan_terakhir = forms.ChoiceField(
        label='Last Experience',
        widget=forms.RadioSelect(
            attrs={
                'id': 'pendidikan_pelamar',
                'class': 'pendidikan'

            }
        ),
        choices=[
            ('MP', 'SMP'),
            ('MA', 'SMA'),
            ('S1', 'Sarjana'),
            ('S2', 'Pascasarjana'),
        ]

    )

Jobseeker/views.py
from django.core import serializers
from django.contrib.auth.models import User
from django.shortcuts import render, HttpResponse, redirect
from .forms import FormPelamar
from django.http import JsonResponse
from .models import Jobseeker
from Kantor.models import Kantor
from django.contrib.auth.models import Group


# Create your views here.


choices = [
    ('1', 'Aceh'),
    ('2', 'Sumatera Utara'),
    ('3', 'Sumatera Barat'),
    ('4', 'Riau'),
    ('5', 'Kepulauan Riau'),
    ('6', 'Bengkulu'),
    ('7', 'Jambi'),
    ('8', 'Sumatera Selatan'),
    ('9', 'Kepulauan Bangka Belitung'),
    ('10', 'Lampung'),
    ('11', 'Banten'),
    ('12', 'Jawa Barat'),
    ('13', 'Dki Jakarta'),
    ('14', 'Jawa Tengah'),
    ('15', 'Di Yogyakarta'),
    ('16', 'Jawa Timur'),
    ('17', 'Bali'),
    ('18', 'Nusa Tenggara Barat'),
    ('19', 'Nusa Tenggara Timur'),
    ('20', 'Kalimantan Timur'),
    ('21', 'Kalimantan Barat'),
    ('22', 'Kalimantan Selatan'),
    ('23', 'Kalimantan Tengah'),
    ('24', 'Kalimantan Utara'),
    ('25', 'Gorontalo'),
    ('26', 'Sulawesi Barat'),
    ('27', 'Sulawesi Tengah'),
    ('28', 'Sulawesi Selatan'),
    ('29', 'Sulawesi Tenggara'),
    ('30', 'Sulawesi Utara'),
    ('31', 'Maluku'),
    ('32', 'Maluku Utara'),
    ('33', 'Papua Barat'),
    ('34', 'Papua'),
]
CHOICES_CLEANED = []
for i in choices:
    CHOICES_CLEANED.append(i[1])


def listDilamar(request):
    passed_group1 = Group.objects.get(name="Jobseeker")
    # passed_group2 => ntar ini buat group buat Kantor yaaa ichsan

    if passed_group1 in request.user.groups.all():
        context = {}
        all_pekerjaan = Kantor.objects.all()
        listCleared = []
        for i in all_pekerjaan:
            if i in Jobseeker.objects.get(nama_pelamar=request.user.username).pekerjaan_dilamar.all():
                listCleared.append(i)

        context['pekerjaans'] = listCleared

        return render(request, 'Jobseeker/listDilamar.html', context)
    else:
        return render(request, 'gagal.html', {'allowed': 'Jobseeker '})


def ajaxFtime(request):
    print()
    return JsonResponse(serializers.serialize('json', Jobseeker.objects.get(
        nama_pelamar=request.user.username).pekerjaan_dilamar.filter(tipe_pekerjaan="Fulltime")), safe=False)


def ajaxPtime(request):
    return JsonResponse(serializers.serialize('json', Jobseeker.objects.get(
        nama_pelamar=request.user.username).pekerjaan_dilamar.filter(tipe_pekerjaan="Part time")), safe=False)


def ajaxIntern(request):
    return JsonResponse(serializers.serialize('json', Jobseeker.objects.get(
        nama_pelamar=request.user.username).pekerjaan_dilamar.filter(tipe_pekerjaan="Internship")), safe=False)


def testFrontEnd(request, job_id):
    pelamar = Jobseeker.objects.get(user=request.user)
    kantor_dilamar = Kantor.objects.get(pk=job_id)
    if request.method == "POST":
        Jobseeker.objects.get(
            user=request.user).pekerjaan_dilamar.add(kantor_dilamar)
        return JsonResponse(serializers.serialize('json', Jobseeker.objects.filter(
            user=request.user)), safe=False)
    else:
        print(pelamar.umur_pelamar == None)
        if pelamar.umur_pelamar == None or pelamar.provinsi_pelamar == None or pelamar.kota_pelamar == None or pelamar.pendidikan_terakhir == None:
            return redirect('/login/editProfile')
        return render(request, 'Jobseeker/melamar.html', {'listProvinsi': CHOICES_CLEANED, 'pekerjaan': kantor_dilamar})

Jobseeker/templates/Jobseeker/editJobseeker.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'Jobseeker/css/Jobseeker.css'%}">
    <link rel="stylesheet" href="{% static 'Jobseeker/css/bootstrap.css'%}">
</head>

<body>

    <nav style="background-color: #0077B650; font-family:Roboto" class="navbar navbar-light navbar-expand ">
        <a style="font-size: 200%;" class="navbar-brand text-lg-center" href="/">Kami <span
                style="color: #E2696A; margin-right:5%;">
                Bisa
            </span>
        </a>
    </nav>
    <div>
        <img src="{% static 'Jobseeker/img/bg_kerja.jpg' %}" alt="" class="bg">

        <div class="formFlex">
            <div class="cardd">
                <div style="background-color: #f6f6f6;" class="containerr">
                    <div>
                        {% if status == 'ditemukan' %}

                        <h1 class="textJudul">Edit profil kamu!</h1>
                        {% else %}
                        <h1 class="textJudul">Lengkapi profil kamu!</h1>
                        {% endif %}

                    </div>
                    <div style="font-family:Roboto" class="formnya">
                        <form method="">
                            {%csrf_token%}
                            <div class="form-group">
                                <label for="id_nama_pelamar">Nama:</label>
                                <input type="text" name="nama_pelamar" value="{{user}}" class="form-control"
                                    maxlength="64" readonly required id="id_nama_pelamar">
                            </div>
                            <div class="form-group">
                                {{form.umur_pelamar.label_tag}}
                                {{form.umur_pelamar}}
                            </div>
                            <div class="form-group">
                                <label for="provinsi_pelamar">Asal Provinsi:</label>
                                <br>
                                <!-- {{nomor_prov}} -->
                                <select id="provinsi_pelamar" name="provinsi_pelamar" class="form-control">
                                    {% for provinsi in listProvinsi %}
                                    <!-- {{forloop.counter}} -->
                                    {% if nomor_prov == forloop.counter%}

                                    <option id="prov{{forloop.counter}}" value="{{forloop.counter}}" selected>
                                        {{provinsi}}</option>
                                    {% else %}
                                    <option id="prov{{forloop.counter}}" value="{{forloop.counter}}">{{provinsi}}
                                    </option>

                                    {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group autocomplete">
                                {{form.kota_pelamar.label_tag}}
                                {{form.kota_pelamar}}
                            </div>
                            <div class="form-group">
                                <div style="display: flex; margin:2px">
                                    {{form.pendidikan_terakhir.label_tag}}
                                    <div style="display: flex; flex-direction:column; margin-left:2%;">
                                        {% for type in form.pendidikan_terakhir %}
                                        <div class="form-group-input">
                                            {{type.tag}}
                                            <label for="{{type.id_for_label}}">
                                                {{type.choice_label}}
                                            </label>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <!-- <button id="btnJobseeker" type="submit">Submit</button> -->
                        </form>
                        <input type="submit" value="Submit" id="btnJobseeker">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class=" alert success flex align-items-center justify-content-center">
        <span class="closebtn">&times;</span>
        <strong>Berhasil!</strong>
        <p id="umur_pelamar_conf">Umur pelamar: </p>
        <p id="kota_pelamar_conf">Kota pelamar: </p>
        <p id="provinsi_pelamar_conf">Provinsi pelamar: </p>
        <p id="last_ed_conf">Last ed: </p>

    </div>
</body>
<script src="{% static 'vendor/jquery/jquery.js'%}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
<script src="{% static 'Jobseeker/js/Jobseeker.js' %}">
</script>
<script>
    $(document).ready(function () {
        $('.closebtn').on('click', function () {
            window.location = '/';
        })
    });
</script>

</html>

Jobseeker/templates/Jobseeker/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <a href="{%url 'daftar_kerja' job_id=1%}"> woi </a>
</body>

</html>

Jobseeker/templates/Jobseeker/listDilamar.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KamiBisa - List Lowongan Pekerjaan</title>
    <link rel="stylesheet" href="{% static 'Kantor/css/Jobseeker.css'%}">
    <link rel="stylesheet" href="{% static 'Jobseeker/css/bootstrap.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'TK1_PPW/css/basic.css'%}">
</head>

<body>
    <nav style="background-color: #0077B650; font-family:Roboto" class="navbar navbar-light navbar-expand ">
        <a style="font-size: 200%;" class="navbar-brand text-lg-center" href="/">Kami <span
                style="color: #E2696A; margin-right:5%;">
                Bisa
            </span>
        </a>
    </nav>
    <div>
        <h1 style="color: black;text-align:center;">Pekerjaan yang telah {{user}} lamar</h1>
    </div>
    <div style="width: 95vw; margin-bottom:100px" class=" d-flex flex-row-reverse navku ">
        <div class="d-flex flex-column bg-blue-400">
            <button style="background-color: rgb(255, 255, 255);" id="btnNav">
                <span>All<i class="fa fa-angle-down"></i></span>
            </button>
            <div style="background-color: rgba(0, 0, 0, 0.582); color:white" class="isiNav flex flex-col ">
                <div>

                    <a id="reset" style="color: white;" href="#">
                        All
                    </a>
                </div>
                <div>

                    <a id="fTime" style="color: white;" href="#">
                        Full-time
                    </a>
                </div>
                <div>
                    <a id="pTime" style="color: white;" href="#">
                        Part-time
                    </a>
                </div>
                <div>
                    <a id="intern" style="color: white;" href="#">
                        Internship
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="table">
        <table style="font-family: Kanit;width: 100%;">
            <tr style="text-align:center;">
                <th>Nama Pekerjaan</th>
                <th>Alamat</th>
                <th>Tipe Pekerjaan</th>
                <th>Tersedia Sejak</th>
            </tr>

            {% for pekerjaan in pekerjaans %}
            <tr style="text-align: center;" class=" text-sm-center">
                <td>
                    <a class="link-web" href="{% url 'detail-lowongan' pekerjaan.pk %}">
                        <p style="color: blue;">{{ pekerjaan.nama_pekerjaan }}</p>
                    </a>
                </td>
                <td>{{ pekerjaan.alamat }} </td>
                <td>{{ pekerjaan.tipe_pekerjaan }} </td>
                <td>{{ pekerjaan.tersedia_sejak }}</td>
            </tr>
            {% endfor %}

        </table>
    </div>

    </div>

    </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $('#btnNav').click(function () {
            if ($(this).hasClass('active')) {
                $(this).removeClass('active')
                $('.isiNav').slideUp();

            } else {
                $(this).addClass('active')
                $('.isiNav').slideDown();
            }
        })


        $('#fTime').on('click', function () {
            $.ajax({
                type: 'GET',
                url: '/Jobseeker/listDilamar/ajaxFtime',
                success: function (response) {
                    let data = JSON.parse(response)
                    $('.table').empty()
                    let x = "<table style='font-family: Kanit;width: 100%;'>" + "<tr style = 'text-align:center;'>"
                        + "<th> Nama Pekerjaan</th>" +
                        '<th>Alamat</th>' +
                        '<th>Tipe Pekerjaan</th>'
                    '<th>Tersedia Sejak</th>'
                        + "</tr> "
                    for (let i = 0; i < data.length; i++) {
                        let temp = data[i].pk
                        x += '<tr style="text-align: center;" class=" text-sm-center">' + '<td> ' +
                            '<p style="color: blue;">' + data[i].fields.nama_pekerjaan + '</p></a></td>' +
                            '<td>' + data[i].fields.alamat + ' </td>' +
                            '<td>' + data[i].fields.tipe_pekerjaan + ' </td>' +
                            '</tr>'
                    }
                    $('.table').append(x)
                    $('#btnNav').text('Full-Time')
                }
            })
        })

        $('#intern').on('click', function () {
            $.ajax({
                type: 'GET',
                url: '/Jobseeker/listDilamar/ajaxIntern',
                success: function (response) {
                    let data = JSON.parse(response)
                    $('.table').empty()
                    let x = "<table style='font-family: Kanit;width: 100%;'>" + "<tr style = 'text-align:center;'>"
                        + "<th> Nama Pekerjaan</th>" +
                        '<th>Alamat</th>' +
                        '<th>Tipe Pekerjaan</th>'
                    '<th>Tersedia Sejak</th>'
                        + "</tr> "
                    for (let i = 0; i < data.length; i++) {
                        let temp = data[i].pk
                        x += '<tr style="text-align: center;" class=" text-sm-center">' + '<td> ' +
                            '<p style="color: blue;">' + data[i].fields.nama_pekerjaan + '</p></a></td>' +
                            '<td>' + data[i].fields.alamat + ' </td>' +
                            '<td>' + data[i].fields.tipe_pekerjaan + ' </td>' +
                            '</tr>'
                    }
                    $('.table').append(x)
                    $('#btnNav').text('Internship')

                }
            })
        })

        $('#pTime').on('click', function () {
            $.ajax({
                type: 'GET',
                url: '/Jobseeker/listDilamar/ajaxPtime',
                success: function (response) {
                    let data = JSON.parse(response)
                    $('.table').empty()
                    let x = "<table style='font-family: Kanit;width: 100%;'>" + "<tr style = 'text-align:center;'>"
                        + "<th> Nama Pekerjaan</th>" +
                        '<th>Alamat</th>' +
                        '<th>Tipe Pekerjaan</th>'
                    '<th>Tersedia Sejak</th>'
                        + "</tr> "
                    for (let i = 0; i < data.length; i++) {
                        let temp = data[i].pk
                        x += '<tr style="text-align: center;" class=" text-sm-center">' + '<td> ' +
                            '<p style="color: blue;">' + data[i].fields.nama_pekerjaan + '</p></a></td>' +
                            '<td>' + data[i].fields.alamat + ' </td>' +
                            '<td>' + data[i].fields.tipe_pekerjaan + ' </td>' +
                            '</tr>'
                    }
                    $('.table').append(x)
                    $('#btnNav').text('Part-time')

                }
            })
        })

        $('#reset').on('click', function () {

            window.location = '/Jobseeker/listDilamar'
        })
    });



</script>

</html>

Jobseeker/templates/Jobseeker/melamar.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'Jobseeker/css/Jobseeker.css'%}">
    <link rel="stylesheet" href="{% static 'Jobseeker/css/bootstrap.css'%}">
</head>
<nav style="background-color: #0077B650; font-family:Roboto" class="navbar navbar-light navbar-expand ">
    <a style="font-size: 200%;" class="navbar-brand text-lg-center" href="/">Kami <span
            style="color: #E2696A; margin-right:5%;">
            Bisa
        </span>
    </a>
</nav>
<form style="display: none;" method="">
    {%csrf_token%}
</form>

<body style="background-color: rgba(245, 245, 245, 0.712);">
    <div style="border: 1px solid black;width:50%;margin:0 auto;" class="mt-4 shadow p-3 mb-5 bg-white rounded">

        <div class=" mt-5 text-center">
            <h1 style="font-size: medium;">Apakah anda yakin ingin melamar sebagai {{pekerjaan.nama_pekerjaan}}? </h1>
        </div>
        <div style="display:flex;margin:0 auto" class="align-items-center justify-content-between w-50 mt-3">
            <a id="yesButton" data-ajax="{{user}}" data-toggle="modal" data-target="#exampleModalCenter">
                <button style="width: 250%;" class='mb-5 btnJobseeker'>Ya</button>
            </a>
            <a href="{% url 'list-lowongan' %}">
                <button style="background-color: red;" class="mb-5 btnJobseeker ">Tidak</button>
            </a>
        </div>
    </div>
</body>


<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="exampleModalLongTitle">Success</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h2 id="namatoadd">Selamat </h2>
                <h3>Berhasil melamar sebagai {{pekerjaan.nama_pekerjaan}}</h3>
            </div>

        </div>
    </div>
</div>
<script src="{% static 'vendor/jquery/jquery.js'%}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $('#yesButton').on('click', function () {
            $.ajax({
                type: 'POST',
                data: {
                    user_login: $(this).attr('data-ajax'),
                    csrfmiddlewaretoken: $('input[name = csrfmiddlewaretoken]').val(),
                },
                success: function (response) {
                    let a = JSON.parse(response)

                    $('#namatoadd').append(a[0].fields.nama_pelamar)
                }
            })

        })
        $('.close').on('click', function () {
            window.location = '/'
        })
    });
</script>

</html>