Perawat/urls.py
from django.urls import path
from Perawat.views import daftar_perawat, detail_perawat, approve_perawat, reject_perawat, finish_perawat

urlpatterns = [
    path('daftar-perawat/<int:id>', daftar_perawat, name='daftarperawat'),
    path('detail/<int:id>', detail_perawat, name='detail_perawat'),
    path('approve/<int:rumah_sakit_id>/<int:id>', approve_perawat, name='approve_perawat'),
    path('reject/<int:rumah_sakit_id>/<int:id>', reject_perawat, name='reject_perawat'),
    path('finish/<int:rumah_sakit_id>/<int:id>', finish_perawat, name='finish_perawat'),
]

TK_PPW_C09/urls.py
from django.contrib import admin
from django.urls import path, include
from TK1_PPW import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('TK1_PPW.urls'), name='LandingPage'),
    path('Jobseeker/', include('Jobseeker.urls'), name='Jobseeker'),
    path('Kantor/', include('Kantor.urls'), name='Kantor'),
    path('VolunteerNonPerawat/', include('VolunteerNonPerawat.urls'),
         name='VolunteerNonPerawat'),
    path('RumahSakit/', include('RumahSakit.urls'), name='RumahSakit'),
    path('Perawat/', include('Perawat.urls'), name='Perawat'),
    path('login/', include('login.urls'), name='login')
]

login/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('', views.index, name='story9index'),
    path('register/', views.register, name="register"),
    path('login/', views.loginCustom, name='login'),
    path('logout/', views.logoutCustom, name='logout'),
    path('editProfile/', views.editProfile, name='editProfile'),
    path('rLogout/', views.rLogout, name='registerLogout')
]

Perawat/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from RumahSakit.models import RS
from django.contrib.auth.models import User 

class Perawat(models.Model):
    PROVINSI = (
        ('1', 'Aceh'),
        ('2', 'Sumatra Utara'),
        ('3', 'Sumatra Barat'),
        ('4', 'Riau'),
        ('5', 'Kepulauan Riau'),
        ('6', 'Bengkulu'),
        ('7', 'Jambi'),
        ('8', 'Sumatra Selatan'),
        ('9', 'Bangka Belitung'),
        ('10', 'Lampung'),
        ('11', 'Banten'),
        ('12', 'Jawa Barat'),
        ('13', 'DKI Jakarta'),
        ('14', 'Jawa Tengah'),
        ('15', 'Yogyakarta'),
        ('16', 'Jawa Timur'),
        ('17', 'Bali'),
        ('18', 'NTB'),
        ('19', 'NTT'),
        ('20', 'Kalimantan Timur'),
        ('21', 'Kalimantan Barat'),
        ('22', 'Kalimantan Selatan'),
        ('23', 'Kalimantan Tengah'),
        ('24', 'Kalimantan Utara'),
        ('25', 'Gorontalo'),
        ('26', 'Sulawesi Barat'),
        ('27', 'Sulawesi Tengah'),
        ('28', 'Sulawesi Selatan'),
        ('29', 'Sulawesi Tenggara'),
        ('30', 'Sulawesi Utara'),
        ('31', 'Maluku'),
        ('32', 'Maluku Utara'),
        ('33', 'Papua Barat'),
        ('34', 'Papua'),
    )
    nama = models.CharField(max_length=100, null=True)
    umur = models.IntegerField(
        validators=[
            MaxValueValidator(55),
            MinValueValidator(17)
        ], null=True)
    email = models.EmailField(null=True)
    provinsi = models.CharField(max_length=2, choices=PROVINSI, null=True)
    kota = models.CharField(max_length=50, null=True)
    no_telp = models.IntegerField(
        validators=[
            MaxValueValidator(999999999999),
            MinValueValidator(99999)
        ], null=True)
    pengalaman = models.TextField(null=True)
    alasan = models.TextField(null=True)
    rumah_sakit = models.ForeignKey(RS, on_delete=models.CASCADE, null = True, blank = True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null = True)
    approval = models.BooleanField(null=True)

Perawat/forms.py
from django.forms import ModelForm, TextInput, NumberInput, EmailInput
from django import forms
from Perawat.models import Perawat

class FormPerawat(ModelForm):
    class Meta:
        PROVINSI = (
        ('1', 'Aceh'),
        ('2', 'Sumatra Utara'),
        ('3', 'Sumatra Barat'),
        ('4', 'Riau'),
        ('5', 'Kepulauan Riau'),
        ('6', 'Bengkulu'),
        ('7', 'Jambi'),
        ('8', 'Sumatra Selatan'),
        ('9', 'Bangka Belitung'),
        ('10', 'Lampung'),
        ('11', 'Banten'),
        ('12', 'Jawa Barat'),
        ('13', 'DKI Jakarta'),
        ('14', 'Jawa Tengah'),
        ('15', 'Yogyakarta'),
        ('16', 'Jawa Timur'),
        ('17', 'Bali'),
        ('18', 'NTB'),
        ('19', 'NTT'),
        ('20', 'Kalimantan Timur'),
        ('21', 'Kalimantan Barat'),
        ('22', 'Kalimantan Selatan'),
        ('23', 'Kalimantan Tengah'),
        ('24', 'Kalimantan Utara'),
        ('25', 'Gorontalo'),
        ('26', 'Sulawesi Barat'),
        ('27', 'Sulawesi Tengah'),
        ('28', 'Sulawesi Selatan'),
        ('29', 'Sulawesi Tenggara'),
        ('30', 'Sulawesi Utara'),
        ('31', 'Maluku'),
        ('32', 'Maluku Utara'),
        ('33', 'Papua Barat'),
        ('34', 'Papua'),
    )
        model = Perawat
        fields = [
            'nama',
            'umur',
            'email',
            'provinsi',
            'kota',
            'no_telp',
            'pengalaman',
            'alasan'
        ]
        labels = {
            'pengalaman' : 'Ceritakan pengalaman Anda dalam bidang keperawatan:',
            'alasan' : 'Alasan ingin menjadi relawan:'
        }
        widgets = {
            'nama' : TextInput(attrs={'class':'form-control form-control-sm', 'required': True}),
            'umur' : NumberInput(attrs={'class':'form-control form-control-sm', 'required': True}),
            'email' : EmailInput(attrs={'class':'form-control form-control-sm', 'required': True}),
            'provinsi' : forms.Select(choices=PROVINSI, attrs={'class':'form-control form-control-sm', 'required': True}),
            'kota' : TextInput(attrs={'class':'form-control form-control-sm', 'required': True}),
            'no_telp' : NumberInput(attrs={'class':'form-control form-control-sm', 'required': True}),
            'pengalaman' : forms.Textarea(attrs={'class':'form-control form-control-sm', 'required': True}),
            'alasan' : forms.Textarea(attrs={'class':'form-control form-control-sm', 'required': True}),
        }
        

Perawat/views.py
from django.shortcuts import render, redirect
from Perawat.forms import FormPerawat
from RumahSakit.models import RS
from Perawat.models import Perawat
from django.contrib.auth.models import Group
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse

def daftar_perawat(request, id):
    if request.user.is_authenticated:
        if Group.objects.get(name='VolunteerPerawat') in request.user.groups.all():
            exist = False
            perawat_obj = None
            try:
                perawat_obj = Perawat.objects.get(user = request.user)
                if perawat_obj.rumah_sakit.id == id:
                    messages.error(request, f'Anda sudah terdaftar menjadi Volunteer di {perawat_obj.rumah_sakit.nama}')
                    return redirect('/RumahSakit/listRS/')
            except ObjectDoesNotExist:
                pass
            except AttributeError:
                exist = True
            form  = FormPerawat(request.POST)
            rumahsakit = RS.objects.get(id=id)
            if request.method == 'POST':
                if form.is_valid() and request.method == 'POST':
                    data = form.cleaned_data
                    try:
                        perawat = Perawat.objects.get(user=request.user)
                        perawat.nama = data['nama']
                        perawat.umur = data['umur']
                        perawat.email = data['email']
                        perawat.provinsi = data['provinsi']
                        perawat.kota = data['kota']
                        perawat.no_telp = data['no_telp']
                        perawat.pengalaman = data['pengalaman']
                        perawat.alasan = data['alasan']
                        perawat.rumah_sakit = rumahsakit
                        perawat.user = request.user
                        perawat.save()
                    except ObjectDoesNotExist:
                        perawat = Perawat()
                        perawat.nama = data['nama']
                        perawat.umur = data['umur']
                        perawat.email = data['email']
                        perawat.provinsi = data['provinsi']
                        perawat.kota = data['kota']
                        perawat.no_telp = data['no_telp']
                        perawat.pengalaman = data['pengalaman']
                        perawat.alasan = data['alasan']
                        perawat.rumah_sakit = rumahsakit
                        perawat.user = request.user
                        perawat.save()

                    messages.success(request, f'Anda telah berhasil melamar menjadi VolunteerNonPerawat di {rumahsakit.nama}!')
                    
                    return redirect('/RumahSakit/listRS')
                
                messages.error(request, f'Terdapat kesalahan dalam mengisi form!')
            if exist:
                print(perawat_obj.nama)
                context = {
                    'form' : form,
                    'page_title' : 'Daftar Menjadi Relawan Sekarang',
                    'alr' : exist,
                    'obj' : perawat_obj
                }
                return render(request, 'daftar-perawat.html', context)
            else:
                context = {
                    'form' : form,
                    'page_title' : 'Daftar Menjadi Relawan Sekarang',
                    'alr' : exist
                }
                return render(request, 'daftar-perawat.html', context)
        else:
            messages.error(request, 'Akun Anda bukan merupakan akun VolunteerPerawat, sehingga tidak bisa melamar sebagai VolunteerPerawat')
            return redirect('/RumahSakit/listRS')
    return redirect('/login/login/')

def detail_perawat(request, id):
    perawat = Perawat.objects.get(id = id)
    
    return JsonResponse({
        'id' : perawat.id, 
        'nama' : perawat.nama, 
        'umur' : perawat.umur, 
        'provinsi' : perawat.provinsi, 
        'kota' : perawat.kota, 
        'pengalaman' : perawat.pengalaman, 
        'alasan' : perawat.alasan,
        'rumah_sakit_id' : perawat.rumah_sakit.id,
        'approval' : perawat.approval})

def approve_perawat(request, rumah_sakit_id, id):
    perawat = Perawat.objects.get(id = id)
    rs = RS.objects.get(id = rumah_sakit_id)
    rs.jml_prwt -= 1
    perawat.approval = True
    perawat.save()
    rs.save()

    return JsonResponse({'nama' : perawat.nama})

def reject_perawat(request, rumah_sakit_id, id):
    perawat = Perawat.objects.get(id = id)
    rs = RS.objects.get(id = rumah_sakit_id)
    perawat.approval = False
    perawat.rumah_sakit = None
    perawat.save()
    rs.save()

    return JsonResponse({'nama' : perawat.nama})

def finish_perawat(request, rumah_sakit_id, id):
    perawat = Perawat.objects.get(id = id)
    rs = RS.objects.get(id = rumah_sakit_id)
    rs.jml_prwt += 1
    perawat.approval = False
    perawat.rumah_sakit = None
    perawat.save()
    rs.save()

    return JsonResponse({'nama' : perawat.nama})

Perawat/templates/daftar-perawat.html
{% load static %}
{% load crispy_forms_tags %}
<html>
    <head>
    <title> {{ page_title }} </title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>
    <script
  src="https://code.jquery.com/jquery-3.5.1.js"
  integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
  crossorigin="anonymous"></script>
    <body>
        <nav style="background-color: #0077B650; font-family:Roboto" class="navbar navbar-expand-lg navbar-light ">
            <a style="font-size: 200%; color: #000000" class="navbar-brand text-lg-center" href="/">
                Kami<span style="color: #EB5757; margin-right:5%;">bisa</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav" style="margin-left: auto;">
                <li class="nav-item active">
                    <a class="nav-link" href="/" style="font-size: 200%;">Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            </div>
        </nav>

        <div class='container' style = 'margin-left : auto; margin-right : auto; margin-top : 5em; margin-bottom : 4em; border: solid 1px black; background: #F6F6F6;'>
            <h1 class="col-xl-12 col-lg-12 col-md-12 col-sm-12" style = 'color : green; padding-top : 1em;'>Daftar Menjadi Relawan Sekarang! </h1>
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 center" style = 'padding-top : 1em; padding-bottom : 1em;'>
                <form method = "POST" autocomplete="off">
                    {% csrf_token %}
                    {% if alr %}
                    
                    <input type="hidden" name="nama" value=  {{ obj.nama }} >                 
                    <input type="hidden" name="umur" value= {{ obj.umur }}  >                   
                    <input type="hidden" name="email" value= {{ obj.email }} > 
                    <input type="hidden" name="provinsi" value= {{ obj.provinsi }} >                  
                    <input type="hidden" name="kota" value= {{ obj.kota }} >                      
                    <input type="hidden" name="no_telp" value= {{ obj.no_telp }} >
                        
                    <div id="div_id_pengalaman" class="control-group"> 
                        <label for="id_pengalaman" class="control-label requiredField">
                        Ceritakan pengalaman Anda dalam bidang keperawatan:<span class="asteriskField">*</span> </label> 
                        <div class="controls">
                            <textarea name="pengalaman" cols="40" rows="10" class="form-control form-control-sm textarea" required="" id="id_pengalaman"></textarea>
                        </div> 
                    </div>
                    <div id="div_id_alasan" class="control-group"> 
                        <label for="id_alasan" class="control-label requiredField">
                        Alasan ingin menjadi relawan:<span class="asteriskField">*</span> </label> 
                        <div class="controls"> 
                            <textarea name="alasan" cols="40" rows="10" class="form-control form-control-sm textarea" required="" id="id_alasan"></textarea> 
                        </div> 
                    </div>
                    
                    {% else %}
                    {{ form|crispy }}
                    {% endif %}
                    <br>
                    <input class="btn btn-success" type="submit" value="Daftar"> 
                </form>
            </div>
        </div>
        <script src= "{% static 'js/isi.js' %}">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
    </body>